### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by leopiresgoss** [leopiresgoss/second-capstone-project#21]
In this capstone project, we are in a group of two collaborators. 

Student A - @richardoppiyo 
Student B - @leopiresgoss 

The project [link](https://github.com/leopiresgoss/second-capstone-project/projects/1)

**Comment by leopiresgoss** [comment]
Thank you. I updated it.

**Comment by elmar8287** [comment]
Hi, @leopiresgoss.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- [ ] Nice job with creating Kanban board 💯 
- [ ] Your issue created as required 👍 

## Required Changes ♻️

- [ ] Please, consider that all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
<img width="367" alt="Screen Shot 2022-03-07 at 23 52 55" src="https://user-images.githubusercontent.com/49064106/157108141-1dc9e1ba-7ace-4770-8acc-80d8a3d487ff.png">


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
Hi, @leopiresgoss.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leopiresgoss** [comment]
Thank you

**Comment by elmar8287** [comment]
@leopiresgoss wish you success!
